name: Create and Upload Artifacts

on: push

env:
  ARTIFACT_NAME: MyArtifact

jobs:
  create-artifacts: 
    name: create-artifacts
    runs-on: ubuntu-latest
    steps:
    
    -name: Check out code
    uses: actions/checkout@v2
    
    -name: Upload artifact
    uses: actions/upload-artifact@v1.0.0
