name: FirstExercise

on: push
  branches: [main]

jobs:

  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      -name: Step One
       uses: actions/checkout@v2
      -name: Step Two
       run: echo "11/17/2021"
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      -name: Step One
       uses: actions/checkout@v2
      -name: Step Two
       run: echo "11/17/2021"
  job3:
    name: Third Job
    runs-on: macos-latest
    steps:
      -name: Step One
       uses: actions/checkout@v2
      -name: Step Two
       uses: echo "11/17/2021"
  job4:
    name: Fourth Job
    runs-on: ubuntu-latest
    needs: [job1. job2, job3]
