name: FirstExercise

on: push

jobs:

  job_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
  job_windows:
    runs-on: windows-latest
    steps:
       - run: date
  job_macos:
    runs-on: macos-latest
    steps:
      - run: date
  job_dependency:
    needs: [job_ubuntu, job_windows, job_macos]
    runs-on: ubuntu-latest
    steps:
      - run: date
 
